# A Simple RNN inference 

![alt text](/home/arjun/Desktop/GitHub/My-Deep-Dives/4_RNN-LSTM-GRU/image-8.png)

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from print_color import print

In [4]:
X = [torch.randn(1, 512) for _ in range(10)] # Let these be the embeddings of the input
U = torch.rand(512, 512)
W = torch.rand(512, 512)
V = torch.rand(512, 1024)
h_prev = torch.randn(1, 512)

In [7]:
for i in range(len(X)):
    h_now = h_prev@U + X[i]@W
    y = h_now@V
    print(torch.argmax(y, dim=1).item(), color='g')
    h_prev = h_now

725
tensor([725])
725
tensor([725])
725
tensor([725])
725
tensor([725])
0
tensor([0])
0
tensor([0])
0
tensor([0])
0
tensor([0])
0
tensor([0])
0
tensor([0])
